"use strict";
exports.__esModule = true;
exports.CHECK_USER_PROFILE_NAME_ATTEMPT = '[ProfileActions] check user-session Profile nam attempt';
exports.CHECK_USER_PROFILE_NAME_SUCCESS = '[ProfileActions] check user-session Profile name success';
exports.CHECK_USER_PROFILE_NAME_FAILURE = '[ProfileActions] check user-session Profile name failure';
exports.RESET_USER_PROFILE_NAME_VALID = '[ProfileActions] reset user-session Profile name valid';
exports.SET_SELECTED_PROFILE_ID = '[ProfileActions] set selectedUserId in Profile reducer';
exports.GET_USER_PROFILE_ATTEMPT = '[ProfileActions] get user-session Profile attempt';
exports.GET_USER_PROFILE_FAILURE = '[ProfileActions] get user-session Profile failure';
exports.GET_USER_PROFILE_SUCCESS = '[ProfileActions] get user-session Profile success';
exports.EDIT_USER_PROFILE_ATTEMPT = '[ProfileActions] update user-session Profile attempt';
exports.EDIT_USER_PROFILE_SUCCESS = '[ProfileActions] update user-session Profile succes';
exports.EDIT_USER_PROFILE_FAILURE = '[ProfileActions] update user-session Profile failure';
exports.REGISTER_USER_FAILURE = '[ProfileActions] user-session registration failed';
exports.REGISTER_USER_ATTEMPT = '[ProfileActions] user-session registration attempt';
exports.REGISTER_USER_SUCCESS = '[ProfileActions] user-session registration successful';
